[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
perk_protocol = "3L72e4b8wKJ8ReMpLUeXxVNrRGpiK6m4VYxeSnecpNW2"

[registry]
url = "https://api.apr.dev"

[programs.devnet]
perk_protocol = "3L72e4b8wKJ8ReMpLUeXxVNrRGpiK6m4VYxeSnecpNW2"

[programs.mainnet]
perk_protocol = "3L72e4b8wKJ8ReMpLUeXxVNrRGpiK6m4VYxeSnecpNW2"

[provider]
cluster = "mainnet"
wallet = 'C:\Users\pomch\.openclaw\workspace\perk\deployer-keypair.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
