import { PublicKey } from "@solana/web3.js";
import BN from "bn.js";
export declare const PERK_PROGRAM_ID: PublicKey;
export declare const PROTOCOL_SEED: Buffer<ArrayBuffer>;
export declare const MARKET_SEED: Buffer<ArrayBuffer>;
export declare const POSITION_SEED: Buffer<ArrayBuffer>;
export declare const VAULT_SEED: Buffer<ArrayBuffer>;
export declare const TRIGGER_SEED: Buffer<ArrayBuffer>;
export declare const MIN_LEVERAGE = 200;
export declare const MAX_LEVERAGE = 2000;
export declare const LEVERAGE_SCALE = 100;
export declare const MIN_TRADING_FEE_BPS = 3;
export declare const MAX_TRADING_FEE_BPS = 100;
export declare const DEFAULT_TRADING_FEE_BPS = 30;
export declare const LIQUIDATION_FEE_BPS = 100;
export declare const MAINTENANCE_MARGIN_BPS = 500;
export declare const CREATOR_FEE_SHARE_BPS = 1000;
export declare const PRICE_SCALE = 1000000;
export declare const POS_SCALE = 1000000;
export declare const ADL_ONE = 1000000;
export declare const K_SCALE: BN;
export declare const MIN_INITIAL_K: BN;
export declare const DEFAULT_MARKET_CREATION_FEE = 1000000000;
export declare const FUNDING_RATE_PRECISION = 1000000;
export declare const MAX_FUNDING_ITERATIONS = 50;
export declare const MAX_FUNDING_DT = 65535;
export declare const FUNDING_RATE_CAP_BPS = 10;
export declare const PEG_UPDATE_COOLDOWN_SLOTS = 100;
export declare const AMM_PEG_THRESHOLD_BPS = 50;
export declare const ORACLE_STALENESS_SECONDS = 15;
export declare const INSURANCE_EPOCH_SECONDS = 86400;
export declare const INSURANCE_EPOCH_CAP_BPS = 3000;
export declare const WARMUP_PERIOD_SLOTS = 1000;
export declare const MIN_REMAINING_POSITION_SIZE = 100;
export declare const MAX_TRIGGER_ORDER_AGE_SECONDS: number;
export declare const DUST_THRESHOLD = 1000;
export declare const MIN_RECLAIM_DELAY_SLOTS = 1000;
export declare const MAX_TRIGGER_ORDERS = 8;
export declare const BPS_DENOMINATOR = 10000;
export declare const MIN_NONZERO_MM_REQ = 10000;
export declare const MIN_NONZERO_IM_REQ = 20000;
export declare const LIQUIDATOR_SHARE_BPS = 5000;
export declare const TRIGGER_EXECUTION_FEE_BPS = 1;
export declare const MIN_DEPOSIT_AMOUNT = 1000;
export declare const MIN_A_SIDE = 1000;
export declare const PERK_ORACLE_SEED: Buffer<ArrayBuffer>;
export declare const MIN_ORACLE_STALENESS_SECONDS = 5;
export declare const MAX_ORACLE_STALENESS_SECONDS = 300;
export declare const MAX_MIN_SOURCES = 10;
export declare const MAX_ORACLE_PRICE = 1000000000000;
export declare const MIN_PRICE_CHANGE_BPS = 100;
export declare const MAX_PRICE_CHANGE_BPS = 9999;
export declare const MIN_CIRCUIT_BREAKER_BPS = 500;
export declare const MAX_CIRCUIT_BREAKER_BPS = 9999;
export declare const CIRCUIT_BREAKER_WINDOW_SLOTS = 50;
export declare const WINDOW_BAND_MULTIPLIER = 3;
export declare const PYTH_PROGRAM_ID: PublicKey;
export declare const PYTH_SOL_USD_FEED: PublicKey;
//# sourceMappingURL=constants.d.ts.map