"use strict";
// @perk/sdk — TypeScript SDK for the Perk perpetual futures protocol on Solana
Object.defineProperty(exports, "__esModule", { value: true });
exports.FUNDING_RATE_PRECISION = exports.DEFAULT_MARKET_CREATION_FEE = exports.MIN_INITIAL_K = exports.K_SCALE = exports.ADL_ONE = exports.POS_SCALE = exports.PRICE_SCALE = exports.CREATOR_FEE_SHARE_BPS = exports.MAINTENANCE_MARGIN_BPS = exports.LIQUIDATION_FEE_BPS = exports.DEFAULT_TRADING_FEE_BPS = exports.MAX_TRADING_FEE_BPS = exports.MIN_TRADING_FEE_BPS = exports.LEVERAGE_SCALE = exports.MAX_LEVERAGE = exports.MIN_LEVERAGE = exports.TRIGGER_SEED = exports.VAULT_SEED = exports.POSITION_SEED = exports.MARKET_SEED = exports.PROTOCOL_SEED = exports.PERK_PROGRAM_ID = exports.isAboveMaintenanceMargin = exports.calculateNotionalBN = exports.accountEquity = exports.amountToNumber = exports.numberToPrice = exports.priceToNumber = exports.haircutRatio = exports.warmupProgress = exports.fundingRateAnnualized = exports.calculateFee = exports.estimateLiquidationPrice = exports.isLiquidatable = exports.marginRatio = exports.initialMarginBps = exports.calculateNotional = exports.effectivePositionQ = exports.calculateSlippageBps = exports.estimateExecutionPrice = exports.calculateMarkPrice = exports.findPerkOracleAddress = exports.findTriggerOrderAddress = exports.findVaultAddress = exports.findPositionAddress = exports.findMarketAddress = exports.findProtocolAddress = exports.PerkOracleCranker = exports.PerkCranker = exports.PerkClient = void 0;
exports.TriggerOrderType = exports.SideState = exports.OracleSource = exports.Side = exports.MAX_TRIGGER_ORDER_AGE_SECONDS = exports.MIN_A_SIDE = exports.MIN_DEPOSIT_AMOUNT = exports.TRIGGER_EXECUTION_FEE_BPS = exports.LIQUIDATOR_SHARE_BPS = exports.MIN_NONZERO_IM_REQ = exports.MIN_NONZERO_MM_REQ = exports.DUST_THRESHOLD = exports.MIN_RECLAIM_DELAY_SLOTS = exports.MIN_REMAINING_POSITION_SIZE = exports.MAX_FUNDING_DT = exports.PYTH_SOL_USD_FEED = exports.PYTH_PROGRAM_ID = exports.WINDOW_BAND_MULTIPLIER = exports.CIRCUIT_BREAKER_WINDOW_SLOTS = exports.MAX_CIRCUIT_BREAKER_BPS = exports.MIN_CIRCUIT_BREAKER_BPS = exports.MAX_PRICE_CHANGE_BPS = exports.MIN_PRICE_CHANGE_BPS = exports.MAX_ORACLE_PRICE = exports.MAX_MIN_SOURCES = exports.MAX_ORACLE_STALENESS_SECONDS = exports.MIN_ORACLE_STALENESS_SECONDS = exports.PERK_ORACLE_SEED = exports.BPS_DENOMINATOR = exports.MAX_TRIGGER_ORDERS = exports.WARMUP_PERIOD_SLOTS = exports.INSURANCE_EPOCH_CAP_BPS = exports.INSURANCE_EPOCH_SECONDS = exports.ORACLE_STALENESS_SECONDS = exports.AMM_PEG_THRESHOLD_BPS = exports.PEG_UPDATE_COOLDOWN_SLOTS = exports.FUNDING_RATE_CAP_BPS = exports.MAX_FUNDING_ITERATIONS = void 0;
var client_1 = require("./client");
Object.defineProperty(exports, "PerkClient", { enumerable: true, get: function () { return client_1.PerkClient; } });
var cranker_1 = require("./cranker");
Object.defineProperty(exports, "PerkCranker", { enumerable: true, get: function () { return cranker_1.PerkCranker; } });
var oracle_cranker_1 = require("./oracle-cranker");
Object.defineProperty(exports, "PerkOracleCranker", { enumerable: true, get: function () { return oracle_cranker_1.PerkOracleCranker; } });
var pda_1 = require("./pda");
Object.defineProperty(exports, "findProtocolAddress", { enumerable: true, get: function () { return pda_1.findProtocolAddress; } });
Object.defineProperty(exports, "findMarketAddress", { enumerable: true, get: function () { return pda_1.findMarketAddress; } });
Object.defineProperty(exports, "findPositionAddress", { enumerable: true, get: function () { return pda_1.findPositionAddress; } });
Object.defineProperty(exports, "findVaultAddress", { enumerable: true, get: function () { return pda_1.findVaultAddress; } });
Object.defineProperty(exports, "findTriggerOrderAddress", { enumerable: true, get: function () { return pda_1.findTriggerOrderAddress; } });
Object.defineProperty(exports, "findPerkOracleAddress", { enumerable: true, get: function () { return pda_1.findPerkOracleAddress; } });
var math_1 = require("./math");
Object.defineProperty(exports, "calculateMarkPrice", { enumerable: true, get: function () { return math_1.calculateMarkPrice; } });
Object.defineProperty(exports, "estimateExecutionPrice", { enumerable: true, get: function () { return math_1.estimateExecutionPrice; } });
Object.defineProperty(exports, "calculateSlippageBps", { enumerable: true, get: function () { return math_1.calculateSlippageBps; } });
Object.defineProperty(exports, "effectivePositionQ", { enumerable: true, get: function () { return math_1.effectivePositionQ; } });
Object.defineProperty(exports, "calculateNotional", { enumerable: true, get: function () { return math_1.calculateNotional; } });
Object.defineProperty(exports, "initialMarginBps", { enumerable: true, get: function () { return math_1.initialMarginBps; } });
Object.defineProperty(exports, "marginRatio", { enumerable: true, get: function () { return math_1.marginRatio; } });
Object.defineProperty(exports, "isLiquidatable", { enumerable: true, get: function () { return math_1.isLiquidatable; } });
Object.defineProperty(exports, "estimateLiquidationPrice", { enumerable: true, get: function () { return math_1.estimateLiquidationPrice; } });
Object.defineProperty(exports, "calculateFee", { enumerable: true, get: function () { return math_1.calculateFee; } });
Object.defineProperty(exports, "fundingRateAnnualized", { enumerable: true, get: function () { return math_1.fundingRateAnnualized; } });
Object.defineProperty(exports, "warmupProgress", { enumerable: true, get: function () { return math_1.warmupProgress; } });
Object.defineProperty(exports, "haircutRatio", { enumerable: true, get: function () { return math_1.haircutRatio; } });
Object.defineProperty(exports, "priceToNumber", { enumerable: true, get: function () { return math_1.priceToNumber; } });
Object.defineProperty(exports, "numberToPrice", { enumerable: true, get: function () { return math_1.numberToPrice; } });
Object.defineProperty(exports, "amountToNumber", { enumerable: true, get: function () { return math_1.amountToNumber; } });
Object.defineProperty(exports, "accountEquity", { enumerable: true, get: function () { return math_1.accountEquity; } });
Object.defineProperty(exports, "calculateNotionalBN", { enumerable: true, get: function () { return math_1.calculateNotionalBN; } });
Object.defineProperty(exports, "isAboveMaintenanceMargin", { enumerable: true, get: function () { return math_1.isAboveMaintenanceMargin; } });
var constants_1 = require("./constants");
Object.defineProperty(exports, "PERK_PROGRAM_ID", { enumerable: true, get: function () { return constants_1.PERK_PROGRAM_ID; } });
Object.defineProperty(exports, "PROTOCOL_SEED", { enumerable: true, get: function () { return constants_1.PROTOCOL_SEED; } });
Object.defineProperty(exports, "MARKET_SEED", { enumerable: true, get: function () { return constants_1.MARKET_SEED; } });
Object.defineProperty(exports, "POSITION_SEED", { enumerable: true, get: function () { return constants_1.POSITION_SEED; } });
Object.defineProperty(exports, "VAULT_SEED", { enumerable: true, get: function () { return constants_1.VAULT_SEED; } });
Object.defineProperty(exports, "TRIGGER_SEED", { enumerable: true, get: function () { return constants_1.TRIGGER_SEED; } });
Object.defineProperty(exports, "MIN_LEVERAGE", { enumerable: true, get: function () { return constants_1.MIN_LEVERAGE; } });
Object.defineProperty(exports, "MAX_LEVERAGE", { enumerable: true, get: function () { return constants_1.MAX_LEVERAGE; } });
Object.defineProperty(exports, "LEVERAGE_SCALE", { enumerable: true, get: function () { return constants_1.LEVERAGE_SCALE; } });
Object.defineProperty(exports, "MIN_TRADING_FEE_BPS", { enumerable: true, get: function () { return constants_1.MIN_TRADING_FEE_BPS; } });
Object.defineProperty(exports, "MAX_TRADING_FEE_BPS", { enumerable: true, get: function () { return constants_1.MAX_TRADING_FEE_BPS; } });
Object.defineProperty(exports, "DEFAULT_TRADING_FEE_BPS", { enumerable: true, get: function () { return constants_1.DEFAULT_TRADING_FEE_BPS; } });
Object.defineProperty(exports, "LIQUIDATION_FEE_BPS", { enumerable: true, get: function () { return constants_1.LIQUIDATION_FEE_BPS; } });
Object.defineProperty(exports, "MAINTENANCE_MARGIN_BPS", { enumerable: true, get: function () { return constants_1.MAINTENANCE_MARGIN_BPS; } });
Object.defineProperty(exports, "CREATOR_FEE_SHARE_BPS", { enumerable: true, get: function () { return constants_1.CREATOR_FEE_SHARE_BPS; } });
Object.defineProperty(exports, "PRICE_SCALE", { enumerable: true, get: function () { return constants_1.PRICE_SCALE; } });
Object.defineProperty(exports, "POS_SCALE", { enumerable: true, get: function () { return constants_1.POS_SCALE; } });
Object.defineProperty(exports, "ADL_ONE", { enumerable: true, get: function () { return constants_1.ADL_ONE; } });
Object.defineProperty(exports, "K_SCALE", { enumerable: true, get: function () { return constants_1.K_SCALE; } });
Object.defineProperty(exports, "MIN_INITIAL_K", { enumerable: true, get: function () { return constants_1.MIN_INITIAL_K; } });
Object.defineProperty(exports, "DEFAULT_MARKET_CREATION_FEE", { enumerable: true, get: function () { return constants_1.DEFAULT_MARKET_CREATION_FEE; } });
Object.defineProperty(exports, "FUNDING_RATE_PRECISION", { enumerable: true, get: function () { return constants_1.FUNDING_RATE_PRECISION; } });
Object.defineProperty(exports, "MAX_FUNDING_ITERATIONS", { enumerable: true, get: function () { return constants_1.MAX_FUNDING_ITERATIONS; } });
Object.defineProperty(exports, "FUNDING_RATE_CAP_BPS", { enumerable: true, get: function () { return constants_1.FUNDING_RATE_CAP_BPS; } });
Object.defineProperty(exports, "PEG_UPDATE_COOLDOWN_SLOTS", { enumerable: true, get: function () { return constants_1.PEG_UPDATE_COOLDOWN_SLOTS; } });
Object.defineProperty(exports, "AMM_PEG_THRESHOLD_BPS", { enumerable: true, get: function () { return constants_1.AMM_PEG_THRESHOLD_BPS; } });
Object.defineProperty(exports, "ORACLE_STALENESS_SECONDS", { enumerable: true, get: function () { return constants_1.ORACLE_STALENESS_SECONDS; } });
Object.defineProperty(exports, "INSURANCE_EPOCH_SECONDS", { enumerable: true, get: function () { return constants_1.INSURANCE_EPOCH_SECONDS; } });
Object.defineProperty(exports, "INSURANCE_EPOCH_CAP_BPS", { enumerable: true, get: function () { return constants_1.INSURANCE_EPOCH_CAP_BPS; } });
Object.defineProperty(exports, "WARMUP_PERIOD_SLOTS", { enumerable: true, get: function () { return constants_1.WARMUP_PERIOD_SLOTS; } });
Object.defineProperty(exports, "MAX_TRIGGER_ORDERS", { enumerable: true, get: function () { return constants_1.MAX_TRIGGER_ORDERS; } });
Object.defineProperty(exports, "BPS_DENOMINATOR", { enumerable: true, get: function () { return constants_1.BPS_DENOMINATOR; } });
Object.defineProperty(exports, "PERK_ORACLE_SEED", { enumerable: true, get: function () { return constants_1.PERK_ORACLE_SEED; } });
Object.defineProperty(exports, "MIN_ORACLE_STALENESS_SECONDS", { enumerable: true, get: function () { return constants_1.MIN_ORACLE_STALENESS_SECONDS; } });
Object.defineProperty(exports, "MAX_ORACLE_STALENESS_SECONDS", { enumerable: true, get: function () { return constants_1.MAX_ORACLE_STALENESS_SECONDS; } });
Object.defineProperty(exports, "MAX_MIN_SOURCES", { enumerable: true, get: function () { return constants_1.MAX_MIN_SOURCES; } });
Object.defineProperty(exports, "MAX_ORACLE_PRICE", { enumerable: true, get: function () { return constants_1.MAX_ORACLE_PRICE; } });
Object.defineProperty(exports, "MIN_PRICE_CHANGE_BPS", { enumerable: true, get: function () { return constants_1.MIN_PRICE_CHANGE_BPS; } });
Object.defineProperty(exports, "MAX_PRICE_CHANGE_BPS", { enumerable: true, get: function () { return constants_1.MAX_PRICE_CHANGE_BPS; } });
Object.defineProperty(exports, "MIN_CIRCUIT_BREAKER_BPS", { enumerable: true, get: function () { return constants_1.MIN_CIRCUIT_BREAKER_BPS; } });
Object.defineProperty(exports, "MAX_CIRCUIT_BREAKER_BPS", { enumerable: true, get: function () { return constants_1.MAX_CIRCUIT_BREAKER_BPS; } });
Object.defineProperty(exports, "CIRCUIT_BREAKER_WINDOW_SLOTS", { enumerable: true, get: function () { return constants_1.CIRCUIT_BREAKER_WINDOW_SLOTS; } });
Object.defineProperty(exports, "WINDOW_BAND_MULTIPLIER", { enumerable: true, get: function () { return constants_1.WINDOW_BAND_MULTIPLIER; } });
Object.defineProperty(exports, "PYTH_PROGRAM_ID", { enumerable: true, get: function () { return constants_1.PYTH_PROGRAM_ID; } });
Object.defineProperty(exports, "PYTH_SOL_USD_FEED", { enumerable: true, get: function () { return constants_1.PYTH_SOL_USD_FEED; } });
Object.defineProperty(exports, "MAX_FUNDING_DT", { enumerable: true, get: function () { return constants_1.MAX_FUNDING_DT; } });
Object.defineProperty(exports, "MIN_REMAINING_POSITION_SIZE", { enumerable: true, get: function () { return constants_1.MIN_REMAINING_POSITION_SIZE; } });
Object.defineProperty(exports, "MIN_RECLAIM_DELAY_SLOTS", { enumerable: true, get: function () { return constants_1.MIN_RECLAIM_DELAY_SLOTS; } });
Object.defineProperty(exports, "DUST_THRESHOLD", { enumerable: true, get: function () { return constants_1.DUST_THRESHOLD; } });
Object.defineProperty(exports, "MIN_NONZERO_MM_REQ", { enumerable: true, get: function () { return constants_1.MIN_NONZERO_MM_REQ; } });
Object.defineProperty(exports, "MIN_NONZERO_IM_REQ", { enumerable: true, get: function () { return constants_1.MIN_NONZERO_IM_REQ; } });
Object.defineProperty(exports, "LIQUIDATOR_SHARE_BPS", { enumerable: true, get: function () { return constants_1.LIQUIDATOR_SHARE_BPS; } });
Object.defineProperty(exports, "TRIGGER_EXECUTION_FEE_BPS", { enumerable: true, get: function () { return constants_1.TRIGGER_EXECUTION_FEE_BPS; } });
Object.defineProperty(exports, "MIN_DEPOSIT_AMOUNT", { enumerable: true, get: function () { return constants_1.MIN_DEPOSIT_AMOUNT; } });
Object.defineProperty(exports, "MIN_A_SIDE", { enumerable: true, get: function () { return constants_1.MIN_A_SIDE; } });
Object.defineProperty(exports, "MAX_TRIGGER_ORDER_AGE_SECONDS", { enumerable: true, get: function () { return constants_1.MAX_TRIGGER_ORDER_AGE_SECONDS; } });
var types_1 = require("./types");
Object.defineProperty(exports, "Side", { enumerable: true, get: function () { return types_1.Side; } });
Object.defineProperty(exports, "OracleSource", { enumerable: true, get: function () { return types_1.OracleSource; } });
Object.defineProperty(exports, "SideState", { enumerable: true, get: function () { return types_1.SideState; } });
Object.defineProperty(exports, "TriggerOrderType", { enumerable: true, get: function () { return types_1.TriggerOrderType; } });
//# sourceMappingURL=index.js.map